name: Deploy to Skynet

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          
          - uses: ThatTimothy/api-grabber@v1.0.0
          with:
          options: /opt.json

      - name: "Deploy to Skynet"
        uses: SkynetLabs/deploy-to-skynet-action@v2.1.1
        with:
          upload-dir: ./
          try-files: /index.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ secrets.REGISTRY_SEED || '' }}
