name: Refresh Feed
on: [push]
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@v2.1.0
        with:
          endpoint: https://api.gateio.ws/api/v4/spot/tickers?currency_pair=hns_usdt
          configuration: '{ "method": "GET" }'
